### ISSUE TITLE
Preliminary Review of Stage per the 4pm  or so build

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface#19] opened 2020-09-02 21:40 UTC
Overall, looking very Good!

I like the way search "preview" in the Refine area works.  

## Two issues, in case you don't know yet:
1) refine is sticky in a bad way
   - I smart searched for Tuckett 59 entries
   - I selected Turkish, which had one entry.
   - Refined and now down to one listing.
   - Cleared search.
   - Smart searched for Levinson
   - no hits (notice the language filter is still in the URL)
   - Smart searched for Tuckett
   - 1 entry found, the Turkish one.

2) A number of Abstract previews displaying weird with a dark box over some of the text.  Sort of like Redacted!

## Other Comments
1) Most Cited and Most Viewed intervals would be better named more plainly ... I suggest simply "# Times Cited", "# Times Viewed"  People will see that there are intervals and certainly get it.

2) In using Refine, I noticed it's fast enough that it might be better to work without the Refine button.  Why not just update the set as I click on the items?  

3) Search speed is generally pretty good, but some searches can be slower than I'm used to seeing--I think that's just a function of running too small a Solr machine or having too little memory for solr or a too small JVM setting, but certainly for demos we'd want a faster instance.

4) For demo, I'd like to remove one of the Glossary refine areas...I knew those would be similar, and I do want to experiment with it more to see which is better.  Right now, they are almost ALWAYs the same, and that will give a negative impression.  (Or put one of them at the end of the list.)  Yes, when we have an admin, we will be able to configure that, but for demos before that, it's best to remove or move one.)  
  ETA:  As I suspected, Glossary Groups has some better terms.  It may not have as many, but I think I'd keep that one and put the other offline for demos now.  Like other refine fields though, this is a much easier way to tune them than I've had before.

I'll play with it more later.  Exciting progress!

## BTW - It's fun to play with smartsearch this way.  (I've been waiting for that.)  I have only seen it in the OpenAPI interface and in my test programs.  Here's a little exercise (which works, but I do see something I might change):
- Tuckett finds papers by Tuckett
- tuckett searches the text for tuckett.  As implemented: it's not a name if it's not capitalized.  I might change that to be smarter if the name is found in the author list.  thinking about it.
- Obama searches the text for Obama, since it knows that Obama isn't one of the authors in the database.
- Tuckett (2015) finds his papers from 2015
- Pasting in 
```Blackman, J. S. (2019) A Web of Sorrow: Mistrust, Jealousy, Lovelessness, Shamelessness, Regret, and Hopelessness, by Salman Akhtar, Routledge, Abingdon and New York, 2018, 180pp.. American Journal of Psychoanalysis 79:230-233```
 finds that single article.  (I just grabbed it from a result list to try it.  Of course, the issue with this is when you get them in a non-standard formatted source.)

I didn't try other smartsearches because I presume they'd work fine...though I'll start "abusing" it soon to test the server with bad input. :)  However, what we will need to figure out is how to better cue users that they can enter those various things!

**Comment by billdami** [comment] 2020-09-03 14:24
> refine is sticky in a bad way

@nrshapiro so I've been looking into this more deeply to figure out the best way to handle it, its a bit more complex of a problem due to how the refine area auto-refreshes as the user types/changes search criteria in the main Search form, and wanted to get your thoughts on how best to handle it.

The crux of the issue is, is that as the user changes their search criteria, the returned facet values/counts will change, and potentially removes refine options or reduces their count to zero, such that they are no longer displayed in the UI (but are still "selected" in memory). The easiest thing to do here would be just completely clear any Refine option selections as soon as the main Search form criteria changes, OR only deselect/clear refine option selections that are no longer valid (not returned in the new responseInfo, or have a count of zero).

I just want to make sure that behavior like this (clearing refine options automatically as the search form changes) would jive with what you are expecting for the user experience here, or if you had something completely  different in mind.

**Comment by nrshapiro** [comment] 2020-09-03 14:47
@billdami  Yes, it's fine, just clear it if the search form changes.  

Also, I note you hide the facet results with 0 matches, but offer to display them.  That's actually nice for some facets, but if it slows down to do that, you can always set the minimum value for which to return facets in the parameters (it wasn't available in an earlier version of the API faceting, but it's fully supported now).  `facetmincount` is the parameter.  Set it to 1 and the 0 facets will no longer be returned.  May save time when the facet list is large, though I haven't looked at timings.

**Comment by billdami** [comment] 2020-09-03 14:50
> `facetmincount` is the parameter. Set it to 1 and the 0 facets will no longer be returned. May save time when the facet list is large, though I haven't looked at timings.

@nrshapiro that is good to know, thanks. I can just leave it as-is for now if we want, as its something we could easily enable later on if we are seeing issues w/large facet lists or think it results in a better UX.

**Comment by lhorne-gavant** [comment] 2020-09-03 15:40
> 3. Search speed is generally pretty good, but some searches can be slower than I'm used to seeing--I think that's just a function of running too small a Solr machine or having too little memory for solr or a too small JVM setting, but certainly for demos we'd want a faster instance.

Hi @nrshapiro ,
Over the last couple of days I've bumped up the size of all API and Solr machines and was wondering if you were still experiencing slowness? If you could pass along some API URLs that aren't responsive enough, that would be helpful as I try out memory settings. 
Thanks!

**Comment by billdami** [comment] 2020-09-03 15:46
Issues `#1` and `#2`, and Other Comments `#1`, `#2`, and `#4` should be resolved via #20

**Closed** 2020-10-05 00:52 UTC
Labels: prelim comments
